export const en = {
  enter: 'Entrance', emphasis: 'Emphasis', exit: 'Exit', entrancePath: 'Entrance path', exitPath: 'Exit path', emphasisEffects: 'Emphasis effects', line: 'Line',
  pulse: 'Pulse', colorPulse: 'Color pulse', bounce: 'Bounce', teeter: 'Teeter', growShrink: 'Grow/Shrink', spin: 'Spin', blink: 'Blink', wave: 'Wave', wiggle: 'Wiggle', desaturate: 'Desaturate', darken: 'Darken', lighten: 'Lighten', transparency: 'Transparency',
  emphasisEffect: 'Emphasis effect', exportRulesTitle: 'PPT export rules', generatedBy: 'Generated by GalWriter AI', scene: 'Scene', node: 'Node',
} as const;
