import type { Language } from '../../../lib/i18n';
import { renderCopy } from '../video/shared/renderCopy';
import type { WebMenuElement } from '../video/shared/types';

export const buildArchivePageElements = (
  language: Language,
  choiceColor: string,
  choiceTextColor: string,
): WebMenuElement[] => {
  const t = (zh: string, ja: string, en: string) => renderCopy(language, zh, ja, en);
  return [
    {
      id: 'archive-title',
      kind: 'text',
      role: 'title',
      text: t('存档', 'セーブ', 'Save'),
      visible: true,
      x: 8,
      y: 7,
      width: 34,
      height: 9,
      scale: 1,
      rotation: 0,
      fontSize: 28,
      textColor: '#ffffff',
      borderRadius: 0,
    },
    {
      id: 'archive-back',
      kind: 'button',
      role: 'back',
      text: t('返回', '戻る', 'Back'),
      visible: true,
      x: 78,
      y: 7,
      width: 14,
      height: 8,
      scale: 1,
      rotation: 0,
      fontSize: 12,
      textColor: '#ffffff',
      backgroundType: 'solid',
      backgroundColor: 'rgba(255,255,255,0.10)',
      borderColor: 'rgba(255,255,255,0.14)',
      borderRadius: 12,
    },
    {
      id: 'archive-slot',
      kind: 'button',
      role: 'slot',
      text: t('没有存档\\n导出后的网页会在这里显示上次进度。', 'セーブなし\\n書き出し後のWebでは前回の進行がここに表示されます。', 'No save\\nExported web builds show the last progress here.'),
      visible: true,
      x: 25,
      y: 42,
      width: 50,
      height: 16,
      scale: 1,
      rotation: 0,
      fontSize: 14,
      textColor: '#f8fafc',
      backgroundType: 'solid',
      backgroundColor: 'rgba(255,255,255,0.10)',
      borderColor: 'rgba(255,255,255,0.16)',
      borderRadius: 12,
    },
    {
      id: 'archive-new',
      kind: 'button',
      role: 'new',
      text: t('新游戏', '新規ゲーム', 'New Game'),
      visible: true,
      x: 25,
      y: 62,
      width: 50,
      height: 10,
      scale: 1,
      rotation: 0,
      primary: true,
      fontSize: 14,
      textColor: choiceTextColor,
      backgroundType: 'solid',
      backgroundColor: choiceColor,
      borderColor: 'rgba(255,255,255,0.22)',
      borderRadius: 12,
    },
  ];
};

export const buildSettingsPageElements = (
  language: Language,
  choiceColor: string,
  choiceTextColor: string,
): WebMenuElement[] => {
  const t = (zh: string, ja: string, en: string) => renderCopy(language, zh, ja, en);
  return [
    {
      id: 'settings-title',
      kind: 'text',
      role: 'title',
      text: t('设置', '設定', 'Settings'),
      visible: true,
      x: 8,
      y: 7,
      width: 34,
      height: 9,
      scale: 1,
      rotation: 0,
      fontSize: 28,
      textColor: '#ffffff',
      borderRadius: 0,
    },
    {
      id: 'settings-back',
      kind: 'button',
      role: 'back',
      text: t('返回', '戻る', 'Back'),
      visible: true,
      x: 78,
      y: 7,
      width: 14,
      height: 8,
      scale: 1,
      rotation: 0,
      fontSize: 12,
      textColor: '#ffffff',
      backgroundType: 'solid',
      backgroundColor: 'rgba(255,255,255,0.10)',
      borderColor: 'rgba(255,255,255,0.14)',
      borderRadius: 12,
    },
    {
      id: 'settings-auto',
      kind: 'button',
      role: 'auto',
      text: t('自动播放', '自動再生', 'Auto play'),
      visible: true,
      x: 25,
      y: 38,
      width: 50,
      height: 10,
      scale: 1,
      rotation: 0,
      fontSize: 14,
      textColor: '#f8fafc',
      backgroundType: 'solid',
      backgroundColor: 'rgba(255,255,255,0.10)',
      borderColor: 'rgba(255,255,255,0.12)',
      borderRadius: 12,
    },
    {
      id: 'settings-speed',
      kind: 'button',
      role: 'speed',
      text: t('打字速度', 'テキスト速度', 'Text speed'),
      visible: true,
      x: 25,
      y: 52,
      width: 50,
      height: 12,
      scale: 1,
      rotation: 0,
      fontSize: 14,
      textColor: '#f8fafc',
      backgroundType: 'solid',
      backgroundColor: 'rgba(255,255,255,0.10)',
      borderColor: 'rgba(255,255,255,0.12)',
      borderRadius: 12,
    },
    {
      id: 'settings-controls',
      kind: 'button',
      role: 'controls',
      text: t('显示控制栏', '操作表示', 'Show controls'),
      visible: true,
      x: 25,
      y: 68,
      width: 50,
      height: 10,
      scale: 1,
      rotation: 0,
      primary: true,
      fontSize: 14,
      textColor: choiceTextColor,
      backgroundType: 'solid',
      backgroundColor: choiceColor,
      borderColor: 'rgba(255,255,255,0.22)',
      borderRadius: 12,
    },
  ];
};
