const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value) && typeof value === 'object' && !Array.isArray(value);

const webPageSettingKeys = {
  home: [
    'showStartMenu',
    'startMenuTemplate',
    'startMenuBackgroundType',
    'startMenuBackgroundColor',
    'startMenuBackgroundGradientStart',
    'startMenuBackgroundGradientEnd',
    'startMenuBackgroundGradientAngle',
    'startMenuBackgroundGradientShape',
    'startMenuBackgroundGradientStops',
    'startMenuBackgroundImageUrl',
    'startMenuBackgroundVideoUrl',
    'startMenuBackgroundVideoLoop',
    'startMenuBackgroundVideoMuted',
    'startMenuBackgroundVideoFit',
    'startMenuElements',
    'startMenuPlacementBoundsLocked',
    'startMenuPlacementMinX',
    'startMenuPlacementMinY',
    'startMenuPlacementMaxX',
    'startMenuPlacementMaxY',
    'startMenuShowSave',
    'startMenuShowNewGame',
    'startMenuShowSettings',
  ],
  archive: [
    'archiveBackgroundType',
    'archiveBackgroundColor',
    'archiveBackgroundGradientStart',
    'archiveBackgroundGradientEnd',
    'archiveBackgroundGradientAngle',
    'archiveBackgroundGradientShape',
    'archiveBackgroundGradientStops',
    'archiveBackgroundImageUrl',
    'archiveBackgroundVideoUrl',
    'archiveBackgroundVideoLoop',
    'archiveBackgroundVideoMuted',
    'archiveBackgroundVideoFit',
    'archivePageElements',
    'startMenuMusicApplyToArchive',
  ],
  settings: [
    'settingsBackgroundType',
    'settingsBackgroundColor',
    'settingsBackgroundGradientStart',
    'settingsBackgroundGradientEnd',
    'settingsBackgroundGradientAngle',
    'settingsBackgroundGradientShape',
    'settingsBackgroundGradientStops',
    'settingsBackgroundImageUrl',
    'settingsBackgroundVideoUrl',
    'settingsBackgroundVideoLoop',
    'settingsBackgroundVideoMuted',
    'settingsBackgroundVideoFit',
    'settingsPageElements',
    'startMenuMusicApplyToSettings',
  ],
  dialogue: [
    'layoutMode',
    'sceneFit',
    'sceneScale',
    'sceneScaleX',
    'sceneScaleY',
    'sceneOffsetX',
    'sceneOffsetY',
    'sceneBackgroundVisible',
    'sceneBackgroundType',
    'sceneBackgroundColor',
    'sceneBackgroundGradientStart',
    'sceneBackgroundGradientEnd',
    'sceneBackgroundGradientAngle',
    'sceneBackgroundImageUrl',
    'choicesPosition',
    'skipSingleChoicePopup',
    'autoAdvance',
    'videoAutoPlay',
    'hideCharacterTags',
    'hideSceneTags',
    'dialogueBackgroundType',
    'dialogueBackgroundColor',
    'dialogueBackgroundGradientStart',
    'dialogueBackgroundGradientEnd',
    'dialogueBackgroundGradientAngle',
    'dialogueBackgroundGradientShape',
    'dialogueBackgroundGradientStops',
    'dialogueBackgroundImageUrl',
    'dialogueBackgroundVideoUrl',
    'dialogueBackgroundVideoLoop',
    'dialogueBackgroundVideoMuted',
    'dialogueBackgroundVideoFit',
    'previewToolbarElements',
    'dialogueOverlayElements',
  ],
  flow: [
    'flowOverviewElements',
    'flowOverviewLayoutDirection',
    'flowOverviewView',
    'flowOverviewControlsInitialized',
    'flowOverviewCardSizes',
    'flowOverviewMinimapWidth',
    'flowOverviewMinimapHeight',
    'flowOverviewBackgroundType',
    'flowOverviewBackgroundColor',
    'flowOverviewBackgroundGradientStart',
    'flowOverviewBackgroundGradientEnd',
    'flowOverviewBackgroundGradientAngle',
    'flowOverviewBackgroundGradientShape',
    'flowOverviewBackgroundGradientStops',
    'flowOverviewBackgroundImageUrl',
    'flowOverviewBackgroundVideoUrl',
    'flowOverviewBackgroundVideoLoop',
    'flowOverviewBackgroundVideoMuted',
    'flowOverviewBackgroundVideoFit',
    'flowOverviewBackgroundMusicUrl',
    'flowOverviewMusicVolume',
    'flowOverviewMusicFadeIn',
    'flowOverviewMusicFadeOut',
    'flowOverviewMusicLoop',
  ],
} as const;

export const splitWebExperienceTemplate = (template: unknown) => {
  if (!isRecord(template) || !isRecord(template.settings)) return null;
  const settings = template.settings;
  if (!Array.isArray(settings.startMenuElements)) return null;

  const { settings: _settings, renderStyle, ...shared } = template;
  const pageKeys = new Set<string>(Object.values(webPageSettingKeys).flat());
  const pages = Object.fromEntries(
    Object.entries(webPageSettingKeys).map(([surface, keys]) => [
      surface,
      {
        version: 1,
        surface,
        settings: Object.fromEntries(
          keys.filter((key) => key in settings).map((key) => [key, settings[key]]),
        ),
        ...(surface === 'dialogue' && renderStyle !== undefined ? { renderStyle } : {}),
      },
    ]),
  );
  return {
    manifest: {
      ...shared,
      version: 3,
      kind: 'galwriter-web-template',
      settings: Object.fromEntries(Object.entries(settings).filter(([key]) => !pageKeys.has(key))),
      pages: {
        home: 'pages/home.json',
        archive: 'pages/archive.json',
        settings: 'pages/settings.json',
        dialogue: 'pages/dialogue.json',
        flow: 'pages/flow.json',
      },
    },
    pages,
  };
};
